blank_issues_enabled: false
contact_links:
  - name: "💬 MotoLink Discussions"
    url: "https://github.com/Mysterx1992/MotoLink/discussions"
    about: "Per domande, idee, suggerimenti e confronto con la community."
  - name: "🟢 Community WhatsApp MotoLink Mirroring"
    url: "https://chat.whatsapp.com/BNTmFxXQuOkGdYWHrX2rV0?s=cl&p=a&mlu=4"
    about: "Per supporto e confronto rapido con la community MotoLink."
